export const ENERGIEBESPARING_SHOW_RESET = "ENERGIEBESPARING_SHOW_RESET";
export const ENERGIEBESPARING_SHOW_SET_ERROR =
  "ENERGIEBESPARING_SHOW_SET_ERROR";
export const ENERGIEBESPARING_SHOW_SET_RETRIEVED =
  "ENERGIEBESPARING_SHOW_SET_RETRIEVED";
export const ENERGIEBESPARING_SHOW_SET_HUB_URL =
  "ENERGIEBESPARING_SHOW_SET_HUB_URL";
export const ENERGIEBESPARING_SHOW_TOGGLE_LOADING =
  "ENERGIEBESPARING_SHOW_TOGGLE_LOADING";
