export const ENERGIEBESPARING_CREATE_RESET = "ENERGIEBESPARING_CREATE_RESET";
export const ENERGIEBESPARING_CREATE_SET_CREATED =
  "ENERGIEBESPARING_CREATE_SET_CREATED";
export const ENERGIEBESPARING_CREATE_SET_ERROR =
  "ENERGIEBESPARING_CREATE_SET_ERROR";
export const ENERGIEBESPARING_CREATE_SET_VIOLATIONS =
  "ENERGIEBESPARING_CREATE_SET_VIOLATIONS";
export const ENERGIEBESPARING_CREATE_TOGGLE_LOADING =
  "ENERGIEBESPARING_CREATE_TOGGLE_LOADING";
