export const KLANT_DELETE_RESET = "KLANT_DELETE_RESET";
export const KLANT_DELETE_SET_ERROR = "KLANT_DELETE_SET_ERROR";
export const KLANT_DELETE_SET_DELETED = "KLANT_DELETE_SET_DELETED";
export const KLANT_DELETE_MERCURE_SET_DELETED =
  "KLANT_DELETE_MERCURE_SET_DELETED";
export const KLANT_DELETE_TOGGLE_LOADING = "KLANT_DELETE_TOGGLE_LOADING";
