export const ENERGIEBESPARING_DELETE_RESET = "ENERGIEBESPARING_DELETE_RESET";
export const ENERGIEBESPARING_DELETE_SET_ERROR =
  "ENERGIEBESPARING_DELETE_SET_ERROR";
export const ENERGIEBESPARING_DELETE_SET_DELETED =
  "ENERGIEBESPARING_DELETE_SET_DELETED";
export const ENERGIEBESPARING_DELETE_MERCURE_SET_DELETED =
  "ENERGIEBESPARING_DELETE_MERCURE_SET_DELETED";
export const ENERGIEBESPARING_DELETE_TOGGLE_LOADING =
  "ENERGIEBESPARING_DELETE_TOGGLE_LOADING";
