export const MICROBIT_SHOW_RESET = "MICROBIT_SHOW_RESET";
export const MICROBIT_SHOW_SET_ERROR = "MICROBIT_SHOW_SET_ERROR";
export const MICROBIT_SHOW_SET_RETRIEVED = "MICROBIT_SHOW_SET_RETRIEVED";
export const MICROBIT_SHOW_SET_HUB_URL = "MICROBIT_SHOW_SET_HUB_URL";
export const MICROBIT_SHOW_TOGGLE_LOADING = "MICROBIT_SHOW_TOGGLE_LOADING";
