export const KLANT_SHOW_RESET = "KLANT_SHOW_RESET";
export const KLANT_SHOW_SET_ERROR = "KLANT_SHOW_SET_ERROR";
export const KLANT_SHOW_SET_RETRIEVED = "KLANT_SHOW_SET_RETRIEVED";
export const KLANT_SHOW_SET_HUB_URL = "KLANT_SHOW_SET_HUB_URL";
export const KLANT_SHOW_TOGGLE_LOADING = "KLANT_SHOW_TOGGLE_LOADING";
