export const MICROBIT_CREATE_RESET = "MICROBIT_CREATE_RESET";
export const MICROBIT_CREATE_SET_CREATED = "MICROBIT_CREATE_SET_CREATED";
export const MICROBIT_CREATE_SET_ERROR = "MICROBIT_CREATE_SET_ERROR";
export const MICROBIT_CREATE_SET_VIOLATIONS = "MICROBIT_CREATE_SET_VIOLATIONS";
export const MICROBIT_CREATE_TOGGLE_LOADING = "MICROBIT_CREATE_TOGGLE_LOADING";
