export const RESET = "MICROBIT_UPDATE_RESET";
export const SET_ERROR = "MICROBIT_UPDATE_SET_ERROR";
export const SET_RETRIEVED = "MICROBIT_UPDATE_SET_RETRIEVED";
export const SET_HUB_URL = "MICROBIT_UPDATE_SET_HUB_URL";
export const SET_UPDATED = "MICROBIT_UPDATE_SET_UPDATED";
export const SET_VIOLATIONS = "MICROBIT_UPDATE_SET_VIOLATIONS";
export const TOGGLE_LOADING = "MICROBIT_UPDATE_TOGGLE_LOADING";
export const UPDATE_RETRIEVED = "MICROBIT_UPDATE_UPDATE_RETRIEVED";
