export const RESET = "KLANT_UPDATE_RESET";
export const SET_ERROR = "KLANT_UPDATE_SET_ERROR";
export const SET_RETRIEVED = "KLANT_UPDATE_SET_RETRIEVED";
export const SET_HUB_URL = "KLANT_UPDATE_SET_HUB_URL";
export const SET_UPDATED = "KLANT_UPDATE_SET_UPDATED";
export const SET_VIOLATIONS = "KLANT_UPDATE_SET_VIOLATIONS";
export const TOGGLE_LOADING = "KLANT_UPDATE_TOGGLE_LOADING";
export const UPDATE_RETRIEVED = "KLANT_UPDATE_UPDATE_RETRIEVED";
