export const KLANT_CREATE_RESET = "KLANT_CREATE_RESET";
export const KLANT_CREATE_SET_CREATED = "KLANT_CREATE_SET_CREATED";
export const KLANT_CREATE_SET_ERROR = "KLANT_CREATE_SET_ERROR";
export const KLANT_CREATE_SET_VIOLATIONS = "KLANT_CREATE_SET_VIOLATIONS";
export const KLANT_CREATE_TOGGLE_LOADING = "KLANT_CREATE_TOGGLE_LOADING";
