export const MICROBIT_DELETE_RESET = "MICROBIT_DELETE_RESET";
export const MICROBIT_DELETE_SET_ERROR = "MICROBIT_DELETE_SET_ERROR";
export const MICROBIT_DELETE_SET_DELETED = "MICROBIT_DELETE_SET_DELETED";
export const MICROBIT_DELETE_MERCURE_SET_DELETED =
  "MICROBIT_DELETE_MERCURE_SET_DELETED";
export const MICROBIT_DELETE_TOGGLE_LOADING = "MICROBIT_DELETE_TOGGLE_LOADING";
