export const RESET = "ENERGIEBESPARING_UPDATE_RESET";
export const SET_ERROR = "ENERGIEBESPARING_UPDATE_SET_ERROR";
export const SET_RETRIEVED = "ENERGIEBESPARING_UPDATE_SET_RETRIEVED";
export const SET_HUB_URL = "ENERGIEBESPARING_UPDATE_SET_HUB_URL";
export const SET_UPDATED = "ENERGIEBESPARING_UPDATE_SET_UPDATED";
export const SET_VIOLATIONS = "ENERGIEBESPARING_UPDATE_SET_VIOLATIONS";
export const TOGGLE_LOADING = "ENERGIEBESPARING_UPDATE_TOGGLE_LOADING";
export const UPDATE_RETRIEVED = "ENERGIEBESPARING_UPDATE_UPDATE_RETRIEVED";
